export const content = {
  meta: {
    title: 'Marissa N. Abrams — Developer Portfolio',
    description:
      'Marissa N. Abrams is a full stack developer in training and U.S. Army supply specialist in Colorado Springs, Colorado.',
  },
  links: {
    github: 'https://github.com/marissaabrams01',
    resume: '/files/Marissa-Abrams-Resume.pdf',
    email: 'whyphy.abrams@gmail.com',
    emailHref: 'mailto:whyphy.abrams@gmail.com',
  },
  labels: {
    github: 'GitHub',
    resume: 'Resume',
    next: 'NEXT:',
    again: 'AGAIN:',
    viewRepository: 'View repository',
    moreGithub: 'More on github.com/marissaabrams01',
    copied: 'Copied — speak soon',
    copyEmail: 'Copy email address',
    email: 'Email',
    downloadResume: 'Download resume',
    who: 'Who',
    work: 'Work',
    craft: 'Craft',
    record: 'Record',
    honours: 'Honours',
    contact: 'Contact',
    top: 'Back to top',
    progress: 'Portfolio sections',
  },
  home: {
    id: 'top',
    navLabel: 'Portfolio links',
    eyebrow: 'PERSONAL PORTFOLIO / COLORADO SPRINGS, CO',
    nameFirst: 'Marissa',
    nameLast: 'Abrams',
    tagline: [
      'Full stack developer in training',
      'U.S. Army supply specialist',
      'Colorado Springs, CO',
    ],
    photos: [
      {
        src: '/images/roses.svg',
        alt: 'Placeholder still life of roses',
        className: 'hero-roses',
      },
      {
        src: '/images/letters.svg',
        alt: 'Placeholder stack of old letters',
        className: 'hero-letters',
      },
      {
        src: '/images/quill.svg',
        alt: 'Placeholder portrait with a quill and candle',
        className: 'hero-quill',
      },
      {
        src: '/images/window.svg',
        alt: 'Placeholder cathedral window strip',
        className: 'hero-window',
      },
    ],
    terminalCommand: 'git log --oneline',
    terminalProjects: [
      'The Beans Place',
      "Marissa's Website",
      'Barbershop',
      'Training Website',
    ],
    terminalReposLabel: 'REPOSITORIES',
  },
  who: {
    id: 'who',
    traits: [
      { text: 'Disciplined.', accent: false },
      { text: 'Organised.', accent: false },
      { text: 'Accountable.', accent: false },
      { text: 'Curious.', accent: false },
      { text: 'Dependable.', accent: false },
      { text: 'Calm under pressure.', accent: false },
      { text: 'Always learning.', accent: true },
    ],
    profileHeading: 'Marissa N. Abrams',
    profileSubheading: 'Developer in training · Supply Specialist (92Y)',
    bio: 'I’m a U.S. Army Unit Supply Specialist (92Y) and certified armorer. My day job is inventory, property accountability and logistics, where every record has to be right. I’m taking that same attention to detail into code. I’m training as a full stack developer through the Vet Bross program, hold HTML & CSS and JavaScript certifications, and am working toward a bachelor’s in Health Management at UMGC.',
    profileFine:
      'SPECIALIST (SPC/E-4) · ARMY COMMENDATION MEDAL ×2 · ARMY ACHIEVEMENT MEDAL ×1 · SECURITY CLEARANCE',
    currentHeading: 'Currently',
    currentSubheading: 'Open to junior developer roles from 2027',
    currentBody:
      'I’m building React sites, learning the backend, and shipping coursework and personal projects to GitHub. I’m available after my Army separation in March 2027 and excited to grow with a thoughtful team.',
    currentFine: 'COLORADO SPRINGS, CO · AVAILABLE AFTER MARCH 2027',
    faceSketchAlt: 'Single-line face sketch',
    quillSketchAlt: 'Single-line quill sketch',
    next: 'Work',
  },
  work: {
    id: 'work',
    label: 'Selected Work',
    title: 'Four projects, built one commit at a time.',
    leadAccent: 'built',
    more: 'More on github.com/marissaabrams01',
    projects: [
      {
        roman: 'I.',
        category: 'COFFEE SHOP STOREFRONT',
        name: 'The Beans Place',
        description:
          'A React storefront with a scroll-driven hero, ribbon ticker, a showcase of 15 single-origin bags, animated counters, a contact form, and a map.',
        stack: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Leaflet'],
        url: 'https://github.com/marissaabrams01/The-Beans-Place',
        image: '/images/beans.svg',
        imageAlt: 'Placeholder duotone coffee shop storefront artwork',
      },
      {
        roman: 'II.',
        category: 'AI TOOL WEB APP',
        name: "Marissa's Website",
        description:
          'A Next.js app with an OpenAI-powered content generator, authentication, pricing, docs and about pages, markdown content, and a written design spec.',
        stack: [
          'Next.js',
          'TypeScript',
          'OpenAI API',
          'NextAuth',
          'Tailwind CSS',
        ],
        url: 'https://github.com/marissaabrams01/marissa-s-website',
        image: '/images/ai.svg',
        imageAlt: 'Placeholder duotone AI tool website artwork',
      },
      {
        roman: 'III.',
        category: 'LOCAL BUSINESS WEBSITE',
        name: 'Barbershop',
        description:
          'A mobile-first local business site organizing services, pricing, shop hours, and booking details.',
        stack: ['HTML', 'CSS', 'JavaScript'],
        url: 'https://github.com/marissaabrams01/Barbershop',
        image: '/images/barber.svg',
        imageAlt: 'Placeholder duotone barbershop storefront artwork',
      },
      {
        roman: 'IV.',
        category: 'FULL STACK COURSEWORK',
        name: 'Training Website',
        description:
          'A coursework practice site for page layout, responsive design, and JavaScript.',
        stack: ['HTML', 'CSS', 'JavaScript'],
        url: 'https://github.com/marissaabrams01/Training-Website',
        image: '/images/training.svg',
        imageAlt: 'Placeholder duotone responsive training website artwork',
      },
    ],
    next: 'Craft',
  },
  craft: {
    id: 'craft',
    statementBefore:
      'I bring the discipline of military logistics to the web: careful, accountable, and',
    statementAccent: 'built to last.',
    sigil: {
      center: ['Detail', '& Duty'],
      rings: ['Army', 'Code', 'Health'],
      alt: 'Three-loop Venn sigil connecting Army, Code, and Health',
    },
    skills: [
      {
        heading: 'Web Development',
        items: [
          'HTML',
          'CSS',
          'JavaScript',
          'React',
          'Tailwind CSS',
          'Git & GitHub',
          'Full stack (in training)',
        ],
      },
      {
        heading: 'Operations',
        items: [
          'Inventory & asset management',
          'Data entry & databases',
          'Records management',
          'Logistics coordination',
          'Information security awareness',
          'Cross-functional communication',
        ],
      },
    ],
    next: 'Record',
  },
  record: {
    id: 'record',
    label: 'Service Record',
    title: 'Every item counted. Every record right.',
    titleAccent: 'right',
    featured: {
      organization: 'United States Army',
      role: 'Unit Supply Specialist (92Y)',
      rank: 'Specialist (SPC/E-4)',
      period: 'Oct 2023 — Present',
      image: '/images/candles.svg',
      imageAlt: 'Placeholder candelabra photograph',
      duties: [
        'Manage supplies, equipment and property accountability.',
        'Conduct inventories, maintain database and supply records, and resolve discrepancies.',
        'Coordinate logistics with leadership.',
        'Operate LMTVs and JLTVs with inspections and safety procedures.',
      ],
    },
    otherJobs: [
      {
        organization: "Doc's Porchside",
        role: 'Server / Food Prep',
        period: '2022–2023',
        image: '/images/barista.svg',
        imageAlt: 'Placeholder restaurant service photograph',
      },
      {
        organization: 'Private Family',
        role: 'Nanny',
        period: '2022 · 9 months',
        image: '/images/letters.svg',
        imageAlt: 'Placeholder family keepsake photograph',
      },
      {
        organization: 'Your Pie · Grovetown, GA',
        role: 'Cashier / Cook / Prep',
        period: '2018–2020',
        image: '/images/beans.svg',
        imageAlt: 'Placeholder restaurant kitchen photograph',
      },
    ],
    next: 'Honours',
  },
  honours: {
    id: 'honours',
    label: 'Education & Honours',
    statement:
      'Still studying: code by night, health management by day, the Army always.',
    accent: 'code',
    columns: [
      {
        roman: 'i.',
        heading: 'Education',
        items: [
          'University of Maryland Global Campus',
          'B.S. Health Management · in progress',
        ],
      },
      {
        roman: 'ii.',
        heading: 'Training',
        items: ['Vet Bross', 'Full Stack Developer Program · in progress'],
      },
      {
        roman: 'iii.',
        heading: 'Certifications',
        items: ['HTML & CSS', 'JavaScript', 'Army-certified armorer'],
      },
      {
        roman: 'iv.',
        heading: 'Honours',
        items: [
          'Army Commendation Medal · 2 awards',
          'Army Achievement Medal · 1 award',
          'Security clearance',
        ],
      },
    ],
    next: 'Contact',
  },
  contact: {
    id: 'contact',
    title: 'Write',
    body: 'I’m open to junior developer roles, internships and freelance builds for small businesses. Send a note, or grab my resume.',
    copyEmailLabel: 'Copy email address',
    copied: 'Copied — speak soon',
    resume: 'Download resume',
    github: 'GitHub',
    seal: '• MARISSA N. ABRAMS • DEVELOPER •',
    sealAlt: 'Marissa N. Abrams developer seal, return to top',
    sealInitial: 'M',
    footer: '© 2026 Marissa N. Abrams · Colorado Springs, CO',
    next: 'Home',
  },
} as const;

export const sections = [
  { id: content.home.id, label: content.home.nameFirst },
  { id: content.who.id, label: content.labels.who },
  { id: content.work.id, label: content.labels.work },
  { id: content.craft.id, label: content.labels.craft },
  { id: content.record.id, label: content.labels.record },
  { id: content.honours.id, label: content.labels.honours },
  { id: content.contact.id, label: content.labels.contact },
];
